export const GET_LOCATION_INFO_START = 'GET_LOCATION_INFO_START';
export const GET_LOCATION_INFO_SUCCESS = 'GET_LOCATION_INFO_SUCCESS';
export const GET_LOCATION_INFO_FAIL = 'GET_LOCATION_INFO_FAIL';

export const MEDICAL_PRICES = 'MEDICAL_PRICES';
export const SHIPPING_METHOD = 'SHIPPING_METHOD';

export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_IN_CART = 'UPDATE_IN_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAN_CART = 'CLEAN_CART';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const UPDATE_USER_INFO_START = 'UPDATE_USER_INFO_START';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';

export const PREORDER_UPDATE = 'PREORDER_UPDATE';
export const PREORDER_DELETE = 'PREORDER_DELETE';
export const PREORDER_PATCH_START = 'PREORDER_PATCH_START';
export const PREORDER_PATCH_SUCCESS = 'PREORDER_PATCH_SUCCESS';
export const PREORDER_PATCH_FAIL = 'PREORDER_PATCH_FAIL';
export const PREORDER_ERROR_CLEAN = 'PREORDER_ERROR_CLEAN';
export const PREORDER_SAVE_START = 'PREORDER_SAVE_START';
export const PREORDER_SAVE_SUCCESS = 'PREORDER_SAVE_SUCCESS';
export const PREORDER_SAVE_FAIL = 'PREORDER_SAVE_FAIL';
